# ArgoCD Application - GitOps Configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-3tier-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Aexplorer00/EKS_TIER3_APP.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: eks-3tier-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
